// <auto-generated />
using System;
using MP2021_LKLB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MP2021_LKLB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210130142913_All")]
    partial class All
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TopScore")
                        .HasColumnType("real");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "TOMAS123",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "502e17ab-5c9e-46be-b253-3810deaa2274",
                            Email = "tomas.kulhavy@pslib.cz",
                            EmailConfirmed = true,
                            FirstName = "Tomáš",
                            Gender = 0,
                            LastName = "Kulhavý",
                            LockoutEnabled = false,
                            NormalizedEmail = "TOMAS.KULHAVY@PSLIB.CZ",
                            NormalizedUserName = "TOMASLKLB",
                            PasswordHash = "AQAAAAEAACcQAAAAEJZjIuDuluSqEgmN5vDCUNIBdf8vLUXzY4aHKs1bV//tF16YY40WP+sRDyH6V6UPJg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "TomasLKLB"
                        },
                        new
                        {
                            Id = "WOLF",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5649595a-6b8b-48ce-9f56-28474d5de805",
                            Email = "w.sluka@seznam.cz",
                            EmailConfirmed = true,
                            FirstName = "Wolfgang",
                            Gender = 0,
                            LastName = "Sluka",
                            LockoutEnabled = false,
                            NormalizedEmail = "W.SLUKA@SEZNAM.CZ",
                            NormalizedUserName = "WOLF",
                            PasswordHash = "AQAAAAEAACcQAAAAEAjK2ksJNjhMytxK9oLsqKNOC3wq5D6Y+jhP46EgrmYIvoK7002OivbRbDfYGSX4Cg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Wolf"
                        },
                        new
                        {
                            Id = "CICA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3cf3de7a-195b-41a6-8dd3-54f06d51d83b",
                            Email = "meta5@seznam.cz",
                            EmailConfirmed = true,
                            FirstName = "Martin",
                            Gender = 0,
                            LastName = "Cicvárek",
                            LockoutEnabled = false,
                            NormalizedEmail = "META5@SEZNAM.CZ",
                            NormalizedUserName = "CÍCA",
                            PasswordHash = "AQAAAAEAACcQAAAAEIVoPM+qq40TjiKahHL5beSmL7nAQ3vRZO4Mt9IObY/OA8I7YdZMAkQaeEJpxXo/ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Cíca"
                        },
                        new
                        {
                            Id = "LUKASZ",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ace64d63-4b83-44f9-b8f3-e1276f7fa796",
                            Email = "czajkolu@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Lukasz",
                            Gender = 0,
                            LastName = "Czaikowski",
                            LockoutEnabled = false,
                            NormalizedEmail = "CZAJKOLU@GMAIL.COM",
                            NormalizedUserName = "LUKASZ",
                            PasswordHash = "AQAAAAEAACcQAAAAEJBQPeoWSmcDuPZW9+teeSiSzYqV2wMGwxAaV+IA4gRsXGy7Z8dk7pieLpZ1FZqnXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Lukasz"
                        },
                        new
                        {
                            Id = "JANHYB",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "64902d3e-cb1c-4d3b-8799-117187a629c3",
                            Email = "jan.hyb@seznam.cz",
                            EmailConfirmed = true,
                            FirstName = "Jan",
                            Gender = 0,
                            LastName = "Hybner",
                            LockoutEnabled = false,
                            NormalizedEmail = "JAN.HYB@SEZNAM.CZ",
                            NormalizedUserName = "HONZAHYB",
                            PasswordHash = "AQAAAAEAACcQAAAAEK4Gf9XEEYFUxA7GtEOrzq3piyjyv3ZFs7qW6Pvft35IwUU0DKAY9bgj8RTX/cgYVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "HonzaHyb"
                        },
                        new
                        {
                            Id = "ZDENEK",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2d354d0c-4bcf-48f1-9930-5aee2d97f3be",
                            Email = "Zdenek.Ulrych@seznam.cz",
                            EmailConfirmed = true,
                            FirstName = "Zdeněk",
                            Gender = 0,
                            LastName = "Ulrych",
                            LockoutEnabled = false,
                            NormalizedEmail = "ZDENEK.ULRYCH@SEZNAM.CZ",
                            NormalizedUserName = "ZDENEK",
                            PasswordHash = "AQAAAAEAACcQAAAAELB+B6Bk5HgoOUP92MBBg66O6gDUcbQ9OrzH/V+6opXG8ifhWVhiIs8knqzdCwMVAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Zdenek"
                        },
                        new
                        {
                            Id = "PETRZA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77948275-d015-4acf-af82-6d339085c87d",
                            Email = "petr-zajic@volny.cz",
                            EmailConfirmed = true,
                            FirstName = "Petr",
                            Gender = 0,
                            LastName = "Zajíc",
                            LockoutEnabled = false,
                            NormalizedEmail = "PETR-ZAJIC@VOLNY.CZ",
                            NormalizedUserName = "ZAJDA",
                            PasswordHash = "AQAAAAEAACcQAAAAEKUjUDrVOjcHxVtihEcyy6i6Ky+qhW/sjdide/KmhyDgZ2jU+YmGe1N7OS+UeLDEGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Zajda"
                        },
                        new
                        {
                            Id = "PETRHYB",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "94048acc-a326-470d-92c9-05f1734dfcf8",
                            Email = "petr-hybner@seznam.cz",
                            EmailConfirmed = true,
                            FirstName = "Petr",
                            Gender = 0,
                            LastName = "Hybner",
                            LockoutEnabled = false,
                            NormalizedEmail = "PETR-HYBNER@SEZNAM.CZ",
                            NormalizedUserName = "PETRHYB",
                            PasswordHash = "AQAAAAEAACcQAAAAEHcLjgVktVwIYBaevB2M2cZ9C/grE4Z8LXr5qdND6/BmUaZ+3EW8Y/5X452beZ+Bmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "PetrHyb"
                        },
                        new
                        {
                            Id = "RUDA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "befbebc6-0f86-4f24-af24-4d92732ab37f",
                            Email = "patrman.rudolf@seznam.cz",
                            EmailConfirmed = true,
                            FirstName = "Rudolf",
                            Gender = 0,
                            LastName = "Patrman",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATRMAN.RUDOLF@SEZNAM.CZ",
                            NormalizedUserName = "RUDA",
                            PasswordHash = "AQAAAAEAACcQAAAAEN7Tj/GxJ2RtrSx4DfrXqU0bSbOOvN2UnFqmHuaMttbVIBcTEhlVb3KgTPIf/0E5rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Ruda"
                        },
                        new
                        {
                            Id = "MILAN",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ac39836c-baa1-49e4-a0fd-76577a1688c1",
                            Email = "milandvorak.gld@seznam.cz",
                            EmailConfirmed = true,
                            FirstName = "Milan",
                            Gender = 0,
                            LastName = "Dvořák",
                            LockoutEnabled = false,
                            NormalizedEmail = "MILANDVORAK.GLD@SEZNAM.CZ",
                            NormalizedUserName = "MILAN",
                            PasswordHash = "AQAAAAEAACcQAAAAECsMgrVmnRqsnjIk+yWx1KZ5ArKSbVN4cd2cYTCOgU6Dlqo4TtdoIBtWdxIywQZurw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Milan"
                        });
                });

            modelBuilder.Entity("MP2021_LKLB.Models.DataRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("FlightLogId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FlightLogId");

                    b.ToTable("DataRecords");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.Extensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DataRecordsId")
                        .HasColumnType("int");

                    b.Property<string>("ENL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FXA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FixesId")
                        .HasColumnType("int");

                    b.Property<string>("GSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WDI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WVE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataRecordsId")
                        .IsUnique();

                    b.HasIndex("FixesId")
                        .IsUnique();

                    b.ToTable("Extensions");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.Fixes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double?>("Enl")
                        .HasColumnType("float");

                    b.Property<int?>("FixAccuracy")
                        .HasColumnType("int");

                    b.Property<int>("FlightLogId")
                        .HasColumnType("int");

                    b.Property<int?>("GpsAltitude")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("PressureAltitude")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FlightLogId");

                    b.ToTable("Fixes");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.FlightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Callsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetitionClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Copilot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Errors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GliderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoggerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoggerManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoggerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumFlight")
                        .HasColumnType("int");

                    b.Property<string>("Pilot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Security")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FlightLogs");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.FlightLogAnalyse", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("FlightTime")
                        .HasColumnType("time");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<bool>("Topflight")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FlightLogAnalyses");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.FlightTask", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeclarationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("DeclarationTime")
                        .HasColumnType("time");

                    b.Property<long?>("DeclarationTimestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumTurnpoints")
                        .HasColumnType("int");

                    b.Property<string>("TaskNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FlightTasks");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.Points", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("FlightTaskId")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightTaskId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "TOMAS123",
                            RoleId = "ADMIN"
                        },
                        new
                        {
                            UserId = "TOMAS123",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "MILAN",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "RUDA",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "LUKASZ",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "CICA",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "WOLF",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "PETRZA",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "PETRHYB",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "ZDENEK",
                            RoleId = "PILOT"
                        },
                        new
                        {
                            UserId = "JANHYB",
                            RoleId = "PILOT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.PilotRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("PilotRole");

                    b.HasData(
                        new
                        {
                            Id = "ADMIN",
                            ConcurrencyStamp = "68304c85-f3b2-4c86-a78b-cf225c5563f8",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "PILOT",
                            ConcurrencyStamp = "ae497b7f-04bd-421e-b622-cef66b89e621",
                            Name = "Pilot",
                            NormalizedName = "PILOT"
                        });
                });

            modelBuilder.Entity("MP2021_LKLB.Models.DataRecords", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.FlightLog", "FlightLog")
                        .WithMany("DataRecords")
                        .HasForeignKey("FlightLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightLog");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.Extensions", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.DataRecords", "DataRecord")
                        .WithOne("Extension")
                        .HasForeignKey("MP2021_LKLB.Models.Extensions", "DataRecordsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MP2021_LKLB.Models.Fixes", "Fix")
                        .WithOne("Extension")
                        .HasForeignKey("MP2021_LKLB.Models.Extensions", "FixesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataRecord");

                    b.Navigation("Fix");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.Fixes", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.FlightLog", "FlightLog")
                        .WithMany("Fixes")
                        .HasForeignKey("FlightLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightLog");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.FlightLog", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.ApplicationUser", "User")
                        .WithMany("Flights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.FlightLogAnalyse", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.FlightLog", "FlightLog")
                        .WithOne("FlightLogAnalyse")
                        .HasForeignKey("MP2021_LKLB.Models.FlightLogAnalyse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightLog");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.FlightTask", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.FlightLog", "FlightLog")
                        .WithOne("Task")
                        .HasForeignKey("MP2021_LKLB.Models.FlightTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightLog");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.Points", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.FlightTask", "FlightTask")
                        .WithMany("Points")
                        .HasForeignKey("FlightTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightTask");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MP2021_LKLB.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MP2021_LKLB.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MP2021_LKLB.Models.ApplicationUser", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.DataRecords", b =>
                {
                    b.Navigation("Extension");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.Fixes", b =>
                {
                    b.Navigation("Extension");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.FlightLog", b =>
                {
                    b.Navigation("DataRecords");

                    b.Navigation("Fixes");

                    b.Navigation("FlightLogAnalyse");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MP2021_LKLB.Models.FlightTask", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
